### GET USERS
GET http://localhost:3010/api/users

### GET USER
GET http://localhost:3010/api/users/1

### DELETE USER
DELETE http://localhost:3010/api/users/2

### ADD USER
POST http://localhost:3010/api/users
content-type: application/json

{
  "name": "Rogerio Flausino",
  "email": "teste@teste.com",
  "password": "123456",
  "homeTeam": "Curintia",
  "age": "28",
  "height": "1.95"
}

### UPDATE USER
PUT http://localhost:3010/api/users/1
content-type: application/json

{
  "name": "Marcos",
  "homeTeam": "Curintia",
  "password": "123"
}